//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoJot.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal sealed class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoJot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean up tabs.
        /// </summary>
        internal static string Cleanup_ConfirmMessage {
            get {
                return ResourceManager.GetString("Cleanup_ConfirmMessage", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete {0} tab{1}. This cannot be undone..
        /// </summary>
        internal static string Cleanup_ConfirmMessage_One {
            get {
                return ResourceManager.GetString("Cleanup_ConfirmMessage_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This will permanently delete {0} tabs{1}. This cannot be undone..
        /// </summary>
        internal static string Cleanup_ConfirmMessage_Few {
            get {
                return ResourceManager.GetString("Cleanup_ConfirmMessage_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (including {0} pinned).
        /// </summary>
        internal static string Cleanup_ConfirmPinnedNote {
            get {
                return ResourceManager.GetString("Cleanup_ConfirmPinnedNote", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean up tabs.
        /// </summary>
        internal static string Cleanup_ConfirmTitle {
            get {
                return ResourceManager.GetString("Cleanup_ConfirmTitle", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete 0 tabs.
        /// </summary>
        internal static string Cleanup_Delete0 {
            get {
                return ResourceManager.GetString("Cleanup_Delete0", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0} tabs.
        /// </summary>
        internal static string Cleanup_DeleteN {
            get {
                return ResourceManager.GetString("Cleanup_DeleteN", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0} tab.
        /// </summary>
        internal static string Cleanup_DeleteN_One {
            get {
                return ResourceManager.GetString("Cleanup_DeleteN_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0} tabs.
        /// </summary>
        internal static string Cleanup_DeleteN_Few {
            get {
                return ResourceManager.GetString("Cleanup_DeleteN_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean up tabs.
        /// </summary>
        internal static string Cleanup_Header {
            get {
                return ResourceManager.GetString("Cleanup_Header", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Include pinned.
        /// </summary>
        internal static string Cleanup_IncludePinned {
            get {
                return ResourceManager.GetString("Cleanup_IncludePinned", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tabs match this filter.
        /// </summary>
        internal static string Cleanup_NoMatch {
            get {
                return ResourceManager.GetString("Cleanup_NoMatch", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean up older than.
        /// </summary>
        internal static string Cleanup_OlderThan {
            get {
                return ResourceManager.GetString("Cleanup_OlderThan", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Cleanup_UnitDays {
            get {
                return ResourceManager.GetString("Cleanup_UnitDays", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Cleanup_UnitHours {
            get {
                return ResourceManager.GetString("Cleanup_UnitHours", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string Cleanup_UnitMonths {
            get {
                return ResourceManager.GetString("Cleanup_UnitMonths", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to weeks.
        /// </summary>
        internal static string Cleanup_UnitWeeks {
            get {
                return ResourceManager.GetString("Cleanup_UnitWeeks", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Common_Undo {
            get {
                return ResourceManager.GetString("Common_Undo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Confirm_Cancel {
            get {
                return ResourceManager.GetString("Confirm_Cancel", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone to new tab.
        /// </summary>
        internal static string Ctx_Clone {
            get {
                return ResourceManager.GetString("Ctx_Clone", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Ctx_Delete {
            get {
                return ResourceManager.GetString("Ctx_Delete", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete all below.
        /// </summary>
        internal static string Ctx_DeleteAllBelow {
            get {
                return ResourceManager.GetString("Ctx_DeleteAllBelow", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Ctx_Pin {
            get {
                return ResourceManager.GetString("Ctx_Pin", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Ctx_Rename {
            get {
                return ResourceManager.GetString("Ctx_Rename", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as TXT.
        /// </summary>
        internal static string Ctx_SaveTxt {
            get {
                return ResourceManager.GetString("Ctx_SaveTxt", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        internal static string Ctx_Unpin {
            get {
                return ResourceManager.GetString("Ctx_Unpin", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created: {0}.
        /// </summary>
        internal static string Date_CreatedPrefix {
            get {
                return ResourceManager.GetString("Date_CreatedPrefix", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        internal static string Date_JustNow {
            get {
                return ResourceManager.GetString("Date_JustNow", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New note.
        /// </summary>
        internal static string Date_NewNote {
            get {
                return ResourceManager.GetString("Date_NewNote", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today {0}.
        /// </summary>
        internal static string Date_Today {
            get {
                return ResourceManager.GetString("Date_Today", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last updated: {0}.
        /// </summary>
        internal static string Date_UpdatedPrefix {
            get {
                return ResourceManager.GetString("Date_UpdatedPrefix", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Date_Yesterday {
            get {
                return ResourceManager.GetString("Date_Yesterday", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yesterday {0}.
        /// </summary>
        internal static string Date_YesterdayTime {
            get {
                return ResourceManager.GetString("Date_YesterdayTime", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to another desktop.
        /// </summary>
        internal static string Drag_AnotherDesktop {
            get {
                return ResourceManager.GetString("Drag_AnotherDesktop", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Another window was opened on this desktop. You can merge or go back..
        /// </summary>
        internal static string Drag_AnotherWindowOpened {
            get {
                return ResourceManager.GetString("Drag_AnotherWindowOpened", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This desktop already has a JoJot window. What would you like to do?.
        /// </summary>
        internal static string Drag_ConflictMessage {
            get {
                return ResourceManager.GetString("Drag_ConflictMessage", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Desktop {0}.
        /// </summary>
        internal static string Drag_DesktopN {
            get {
                return ResourceManager.GetString("Drag_DesktopN", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From: {0}.
        /// </summary>
        internal static string Drag_From {
            get {
                return ResourceManager.GetString("Drag_From", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string Drag_GoBack {
            get {
                return ResourceManager.GetString("Drag_GoBack", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep here.
        /// </summary>
        internal static string Drag_KeepHere {
            get {
                return ResourceManager.GetString("Drag_KeepHere", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep your notes on this desktop, or go back?.
        /// </summary>
        internal static string Drag_KeepOrGoMessage {
            get {
                return ResourceManager.GetString("Drag_KeepOrGoMessage", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merge notes.
        /// </summary>
        internal static string Drag_MergeNotes {
            get {
                return ResourceManager.GetString("Drag_MergeNotes", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (misplaced).
        /// </summary>
        internal static string Drag_Misplaced {
            get {
                return ResourceManager.GetString("Drag_Misplaced", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Moved to {0}.
        /// </summary>
        internal static string Drag_MovedTo {
            get {
                return ResourceManager.GetString("Drag_MovedTo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Drag_Retry {
            get {
                return ResourceManager.GetString("Drag_Retry", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If retry fails, move this window back manually via Win+Tab.
        /// </summary>
        internal static string Drag_RetryHint {
            get {
                return ResourceManager.GetString("Drag_RetryHint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' contains binary content.
        /// </summary>
        internal static string Drop_Binary {
            get {
                return ResourceManager.GetString("Drop_Binary", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drop file here.
        /// </summary>
        internal static string Drop_FileHere {
            get {
                return ResourceManager.GetString("Drop_FileHere", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text files only, max 500KB.
        /// </summary>
        internal static string Drop_Hint {
            get {
                return ResourceManager.GetString("Drop_Hint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) opened, {1} skipped ({2}).
        /// </summary>
        internal static string Drop_PartialSuccess {
            get {
                return ResourceManager.GetString("Drop_PartialSuccess", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to read '{0}'.
        /// </summary>
        internal static string Drop_ReadFailed {
            get {
                return ResourceManager.GetString("Drop_ReadFailed", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to '{0}' is too large (max 500KB).
        /// </summary>
        internal static string Drop_TooLarge {
            get {
                return ResourceManager.GetString("Drop_TooLarge", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find_Header {
            get {
                return ResourceManager.GetString("Find_Header", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No matches.
        /// </summary>
        internal static string Find_NoMatches {
            get {
                return ResourceManager.GetString("Find_NoMatches", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find_Placeholder {
            get {
                return ResourceManager.GetString("Find_Placeholder", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Find_Replace {
            get {
                return ResourceManager.GetString("Find_Replace", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        internal static string Find_ReplaceAll {
            get {
                return ResourceManager.GetString("Find_ReplaceAll", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string Find_ReplacePlaceholder {
            get {
                return ResourceManager.GetString("Find_ReplacePlaceholder", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone tab.
        /// </summary>
        internal static string Help_CloneTab {
            get {
                return ResourceManager.GetString("Help_CloneTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy (all if no selection).
        /// </summary>
        internal static string Help_Copy {
            get {
                return ResourceManager.GetString("Help_Copy", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Help_Cut {
            get {
                return ResourceManager.GetString("Help_Cut", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete tab.
        /// </summary>
        internal static string Help_DeleteTab {
            get {
                return ResourceManager.GetString("Help_DeleteTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press Escape or click outside to close.
        /// </summary>
        internal static string Help_DismissHint {
            get {
                return ResourceManager.GetString("Help_DismissHint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find in editor / Search tabs.
        /// </summary>
        internal static string Help_Find {
            get {
                return ResourceManager.GetString("Help_Find", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus / minimize JoJot.
        /// </summary>
        internal static string Help_FocusMinimize {
            get {
                return ResourceManager.GetString("Help_FocusMinimize", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decrease font size.
        /// </summary>
        internal static string Help_FontDecrease {
            get {
                return ResourceManager.GetString("Help_FontDecrease", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Increase font size.
        /// </summary>
        internal static string Help_FontIncrease {
            get {
                return ResourceManager.GetString("Help_FontIncrease", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset font size (100%).
        /// </summary>
        internal static string Help_FontReset {
            get {
                return ResourceManager.GetString("Help_FontReset", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        internal static string Help_NewTab {
            get {
                return ResourceManager.GetString("Help_NewTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next tab.
        /// </summary>
        internal static string Help_NextTab {
            get {
                return ResourceManager.GetString("Help_NextTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Help_Paste {
            get {
                return ResourceManager.GetString("Help_Paste", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin / Unpin.
        /// </summary>
        internal static string Help_PinUnpin {
            get {
                return ResourceManager.GetString("Help_PinUnpin", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous tab.
        /// </summary>
        internal static string Help_PreviousTab {
            get {
                return ResourceManager.GetString("Help_PreviousTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string Help_Redo {
            get {
                return ResourceManager.GetString("Help_Redo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo (alt).
        /// </summary>
        internal static string Help_RedoAlt {
            get {
                return ResourceManager.GetString("Help_RedoAlt", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename tab.
        /// </summary>
        internal static string Help_RenameTab {
            get {
                return ResourceManager.GetString("Help_RenameTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as TXT.
        /// </summary>
        internal static string Help_SaveAsTxt {
            get {
                return ResourceManager.GetString("Help_SaveAsTxt", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EDITOR.
        /// </summary>
        internal static string Help_SectionEditor {
            get {
                return ResourceManager.GetString("Help_SectionEditor", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GLOBAL.
        /// </summary>
        internal static string Help_SectionGlobal {
            get {
                return ResourceManager.GetString("Help_SectionGlobal", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TABS.
        /// </summary>
        internal static string Help_SectionTabs {
            get {
                return ResourceManager.GetString("Help_SectionTabs", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string Help_SectionView {
            get {
                return ResourceManager.GetString("Help_SectionView", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string Help_SelectAll {
            get {
                return ResourceManager.GetString("Help_SelectAll", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show this help.
        /// </summary>
        internal static string Help_ShowHelp {
            get {
                return ResourceManager.GetString("Help_ShowHelp", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyboard Shortcuts.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help_Title", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Help_Undo {
            get {
                return ResourceManager.GetString("Help_Undo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zoom (over editor).
        /// </summary>
        internal static string Help_Zoom {
            get {
                return ResourceManager.GetString("Help_Zoom", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clean up tabs.
        /// </summary>
        internal static string Menu_Cleanup {
            get {
                return ResourceManager.GetString("Menu_Cleanup", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Menu_Preferences {
            get {
                return ResourceManager.GetString("Menu_Preferences", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recover sessions.
        /// </summary>
        internal static string Menu_Recover {
            get {
                return ResourceManager.GetString("Menu_Recover", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto-delete after.
        /// </summary>
        internal static string Pref_AutoDelete {
            get {
                return ResourceManager.GetString("Pref_AutoDelete", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Leave blank to disable. Pinned tabs are kept..
        /// </summary>
        internal static string Pref_AutoDeleteHint {
            get {
                return ResourceManager.GetString("Pref_AutoDeleteHint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Pref_Days {
            get {
                return ResourceManager.GetString("Pref_Days", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string Pref_FontSize {
            get {
                return ResourceManager.GetString("Pref_FontSize", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 100%.
        /// </summary>
        internal static string Pref_FontReset {
            get {
                return ResourceManager.GetString("Pref_FontReset", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey.
        /// </summary>
        internal static string Pref_GlobalHotkey {
            get {
                return ResourceManager.GetString("Pref_GlobalHotkey", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Pref_Header {
            get {
                return ResourceManager.GetString("Pref_Header", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Focus JoJot from any app.
        /// </summary>
        internal static string Pref_HotkeyHint {
            get {
                return ResourceManager.GetString("Pref_HotkeyHint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Press keys....
        /// </summary>
        internal static string Pref_HotkeyPressKeys {
            get {
                return ResourceManager.GetString("Pref_HotkeyPressKeys", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Pref_HotkeyRecord {
            get {
                return ResourceManager.GetString("Pref_HotkeyRecord", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Pref_Language {
            get {
                return ResourceManager.GetString("Pref_Language", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restart required to apply.
        /// </summary>
        internal static string Pref_LanguageHint {
            get {
                return ResourceManager.GetString("Pref_LanguageHint", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to APPEARANCE.
        /// </summary>
        internal static string Pref_SectionAppearance {
            get {
                return ResourceManager.GetString("Pref_SectionAppearance", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CLEANUP.
        /// </summary>
        internal static string Pref_SectionCleanup {
            get {
                return ResourceManager.GetString("Pref_SectionCleanup", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        internal static string Pref_SectionLanguage {
            get {
                return ResourceManager.GetString("Pref_SectionLanguage", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SHORTCUTS.
        /// </summary>
        internal static string Pref_SectionShortcuts {
            get {
                return ResourceManager.GetString("Pref_SectionShortcuts", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Pref_Theme {
            get {
                return ResourceManager.GetString("Pref_Theme", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Pref_ThemeDark {
            get {
                return ResourceManager.GetString("Pref_ThemeDark", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Pref_ThemeLight {
            get {
                return ResourceManager.GetString("Pref_ThemeLight", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string Pref_ThemeSystem {
            get {
                return ResourceManager.GetString("Pref_ThemeSystem", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adopt.
        /// </summary>
        internal static string Recovery_Adopt {
            get {
                return ResourceManager.GetString("Recovery_Adopt", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Empty note.
        /// </summary>
        internal static string Recovery_EmptyNote {
            get {
                return ResourceManager.GetString("Recovery_EmptyNote", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recover Sessions.
        /// </summary>
        internal static string Recovery_Header {
            get {
                return ResourceManager.GetString("Recovery_Header", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to +{0} more.
        /// </summary>
        internal static string Recovery_More {
            get {
                return ResourceManager.GetString("Recovery_More", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tabs.
        /// </summary>
        internal static string Recovery_TabCount {
            get {
                return ResourceManager.GetString("Recovery_TabCount", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tab.
        /// </summary>
        internal static string Recovery_TabCount_One {
            get {
                return ResourceManager.GetString("Recovery_TabCount_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tabs.
        /// </summary>
        internal static string Recovery_TabCount_Few {
            get {
                return ResourceManager.GetString("Recovery_TabCount_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unknown desktop.
        /// </summary>
        internal static string Recovery_UnknownDesktop {
            get {
                return ResourceManager.GetString("Recovery_UnknownDesktop", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search tabs....
        /// </summary>
        internal static string Search_Placeholder {
            get {
                return ResourceManager.GetString("Search_Placeholder", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JoJot.
        /// </summary>
        internal static string Title_Default {
            get {
                return ResourceManager.GetString("Title_Default", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JoJot note {0}.txt.
        /// </summary>
        internal static string Title_DefaultFilename {
            get {
                return ResourceManager.GetString("Title_DefaultFilename", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JoJot note.
        /// </summary>
        internal static string Title_DefaultFilenameFallback {
            get {
                return ResourceManager.GetString("Title_DefaultFilenameFallback", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JoJot -- Desktop {0}.
        /// </summary>
        internal static string Title_DesktopN {
            get {
                return ResourceManager.GetString("Title_DesktopN", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to JoJot -- {0}.
        /// </summary>
        internal static string Title_Named {
            get {
                return ResourceManager.GetString("Title_Named", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tabs cleaned up.
        /// </summary>
        internal static string Toast_CleanedUp {
            get {
                return ResourceManager.GetString("Toast_CleanedUp", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tab cleaned up.
        /// </summary>
        internal static string Toast_CleanedUp_One {
            get {
                return ResourceManager.GetString("Toast_CleanedUp_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} tabs cleaned up.
        /// </summary>
        internal static string Toast_CleanedUp_Few {
            get {
                return ResourceManager.GetString("Toast_CleanedUp_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} deleted.
        /// </summary>
        internal static string Toast_Deleted {
            get {
                return ResourceManager.GetString("Toast_Deleted", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Global hotkey ({0}) is in use by another app. Change it in Preferences..
        /// </summary>
        internal static string Toast_HotkeyConflict {
            get {
                return ResourceManager.GetString("Toast_HotkeyConflict", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotkey already in use by another app.
        /// </summary>
        internal static string Toast_HotkeyInUse {
            get {
                return ResourceManager.GetString("Toast_HotkeyInUse", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Merged {0} notes from {1}.
        /// </summary>
        internal static string Toast_Merged {
            get {
                return ResourceManager.GetString("Toast_Merged", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} notes deleted.
        /// </summary>
        internal static string Toast_NotesDeleted {
            get {
                return ResourceManager.GetString("Toast_NotesDeleted", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} note deleted.
        /// </summary>
        internal static string Toast_NotesDeleted_One {
            get {
                return ResourceManager.GetString("Toast_NotesDeleted_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} notes deleted.
        /// </summary>
        internal static string Toast_NotesDeleted_Few {
            get {
                return ResourceManager.GetString("Toast_NotesDeleted_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recovered window from interrupted move.
        /// </summary>
        internal static string Toast_Recovery {
            get {
                return ResourceManager.GetString("Toast_Recovery", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} replacements made.
        /// </summary>
        internal static string Toast_Replacements {
            get {
                return ResourceManager.GetString("Toast_Replacements", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} replacement made.
        /// </summary>
        internal static string Toast_Replacements_One {
            get {
                return ResourceManager.GetString("Toast_Replacements_One", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} replacements made.
        /// </summary>
        internal static string Toast_Replacements_Few {
            get {
                return ResourceManager.GetString("Toast_Replacements_Few", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clone to new tab (Ctrl+K).
        /// </summary>
        internal static string Tooltip_Clone {
            get {
                return ResourceManager.GetString("Tooltip_Clone", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        internal static string Tooltip_Copy {
            get {
                return ResourceManager.GetString("Tooltip_Copy", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete (Ctrl+W).
        /// </summary>
        internal static string Tooltip_Delete {
            get {
                return ResourceManager.GetString("Tooltip_Delete", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Find (Ctrl+F).
        /// </summary>
        internal static string Tooltip_Find {
            get {
                return ResourceManager.GetString("Tooltip_Find", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Tooltip_Menu {
            get {
                return ResourceManager.GetString("Tooltip_Menu", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New tab (Ctrl+T).
        /// </summary>
        internal static string Tooltip_NewTab {
            get {
                return ResourceManager.GetString("Tooltip_NewTab", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string Tooltip_Paste {
            get {
                return ResourceManager.GetString("Tooltip_Paste", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin (Ctrl+P).
        /// </summary>
        internal static string Tooltip_Pin {
            get {
                return ResourceManager.GetString("Tooltip_Pin", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Tooltip_PinShort {
            get {
                return ResourceManager.GetString("Tooltip_PinShort", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        internal static string Tooltip_Redo {
            get {
                return ResourceManager.GetString("Tooltip_Redo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save as TXT (Ctrl+S).
        /// </summary>
        internal static string Tooltip_Save {
            get {
                return ResourceManager.GetString("Tooltip_Save", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        internal static string Tooltip_Undo {
            get {
                return ResourceManager.GetString("Tooltip_Undo", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unpin (Ctrl+P).
        /// </summary>
        internal static string Tooltip_Unpin {
            get {
                return ResourceManager.GetString("Tooltip_Unpin", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        internal static string Tooltip_UnpinShort {
            get {
                return ResourceManager.GetString("Tooltip_UnpinShort", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to JoJot.
        /// </summary>
        internal static string Welcome_Content {
            get {
                return ResourceManager.GetString("Welcome_Content", resourceCulture)!;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome to JoJot.
        /// </summary>
        internal static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture)!;
            }
        }
    }
}
