//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoJot.Resources {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public sealed class Strings {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoJot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        public static string Cleanup_ConfirmMessage {
            get { return ResourceManager.GetString("Cleanup_ConfirmMessage", resourceCulture)!; }
        }

        public static string Cleanup_ConfirmMessage_Few {
            get { return ResourceManager.GetString("Cleanup_ConfirmMessage_Few", resourceCulture)!; }
        }

        public static string Cleanup_ConfirmMessage_One {
            get { return ResourceManager.GetString("Cleanup_ConfirmMessage_One", resourceCulture)!; }
        }

        public static string Cleanup_ConfirmPinnedNote {
            get { return ResourceManager.GetString("Cleanup_ConfirmPinnedNote", resourceCulture)!; }
        }

        public static string Cleanup_ConfirmTitle {
            get { return ResourceManager.GetString("Cleanup_ConfirmTitle", resourceCulture)!; }
        }

        public static string Cleanup_Delete0 {
            get { return ResourceManager.GetString("Cleanup_Delete0", resourceCulture)!; }
        }

        public static string Cleanup_DeleteN {
            get { return ResourceManager.GetString("Cleanup_DeleteN", resourceCulture)!; }
        }

        public static string Cleanup_DeleteN_Few {
            get { return ResourceManager.GetString("Cleanup_DeleteN_Few", resourceCulture)!; }
        }

        public static string Cleanup_DeleteN_One {
            get { return ResourceManager.GetString("Cleanup_DeleteN_One", resourceCulture)!; }
        }

        public static string Cleanup_Header {
            get { return ResourceManager.GetString("Cleanup_Header", resourceCulture)!; }
        }

        public static string Cleanup_IncludePinned {
            get { return ResourceManager.GetString("Cleanup_IncludePinned", resourceCulture)!; }
        }

        public static string Cleanup_NoMatch {
            get { return ResourceManager.GetString("Cleanup_NoMatch", resourceCulture)!; }
        }

        public static string Cleanup_OlderThan {
            get { return ResourceManager.GetString("Cleanup_OlderThan", resourceCulture)!; }
        }

        public static string Cleanup_UnitDays {
            get { return ResourceManager.GetString("Cleanup_UnitDays", resourceCulture)!; }
        }

        public static string Cleanup_UnitHours {
            get { return ResourceManager.GetString("Cleanup_UnitHours", resourceCulture)!; }
        }

        public static string Cleanup_UnitMonths {
            get { return ResourceManager.GetString("Cleanup_UnitMonths", resourceCulture)!; }
        }

        public static string Cleanup_UnitWeeks {
            get { return ResourceManager.GetString("Cleanup_UnitWeeks", resourceCulture)!; }
        }

        public static string Common_Cancel {
            get { return ResourceManager.GetString("Common_Cancel", resourceCulture)!; }
        }

        public static string Common_Delete {
            get { return ResourceManager.GetString("Common_Delete", resourceCulture)!; }
        }

        public static string Common_Undo {
            get { return ResourceManager.GetString("Common_Undo", resourceCulture)!; }
        }

        public static string Confirm_Cancel {
            get { return ResourceManager.GetString("Confirm_Cancel", resourceCulture)!; }
        }

        public static string Confirm_Delete {
            get { return ResourceManager.GetString("Confirm_Delete", resourceCulture)!; }
        }

        public static string Ctx_Clone {
            get { return ResourceManager.GetString("Ctx_Clone", resourceCulture)!; }
        }

        public static string Ctx_Delete {
            get { return ResourceManager.GetString("Ctx_Delete", resourceCulture)!; }
        }

        public static string Ctx_DeleteAllBelow {
            get { return ResourceManager.GetString("Ctx_DeleteAllBelow", resourceCulture)!; }
        }

        public static string Ctx_Pin {
            get { return ResourceManager.GetString("Ctx_Pin", resourceCulture)!; }
        }

        public static string Ctx_Rename {
            get { return ResourceManager.GetString("Ctx_Rename", resourceCulture)!; }
        }

        public static string Ctx_Save {
            get { return ResourceManager.GetString("Ctx_Save", resourceCulture)!; }
        }

        public static string Ctx_SaveAs {
            get { return ResourceManager.GetString("Ctx_SaveAs", resourceCulture)!; }
        }

        public static string Ctx_Unpin {
            get { return ResourceManager.GetString("Ctx_Unpin", resourceCulture)!; }
        }

        public static string Date_CreatedPrefix {
            get { return ResourceManager.GetString("Date_CreatedPrefix", resourceCulture)!; }
        }

        public static string Date_JustNow {
            get { return ResourceManager.GetString("Date_JustNow", resourceCulture)!; }
        }

        public static string Date_NewNote {
            get { return ResourceManager.GetString("Date_NewNote", resourceCulture)!; }
        }

        public static string Date_Today {
            get { return ResourceManager.GetString("Date_Today", resourceCulture)!; }
        }

        public static string Date_UpdatedPrefix {
            get { return ResourceManager.GetString("Date_UpdatedPrefix", resourceCulture)!; }
        }

        public static string Date_Yesterday {
            get { return ResourceManager.GetString("Date_Yesterday", resourceCulture)!; }
        }

        public static string Date_YesterdayTime {
            get { return ResourceManager.GetString("Date_YesterdayTime", resourceCulture)!; }
        }

        public static string Drag_AnotherDesktop {
            get { return ResourceManager.GetString("Drag_AnotherDesktop", resourceCulture)!; }
        }

        public static string Drag_AnotherWindowOpened {
            get { return ResourceManager.GetString("Drag_AnotherWindowOpened", resourceCulture)!; }
        }

        public static string Drag_ConflictMessage {
            get { return ResourceManager.GetString("Drag_ConflictMessage", resourceCulture)!; }
        }

        public static string Drag_DesktopN {
            get { return ResourceManager.GetString("Drag_DesktopN", resourceCulture)!; }
        }

        public static string Drag_From {
            get { return ResourceManager.GetString("Drag_From", resourceCulture)!; }
        }

        public static string Drag_GoBack {
            get { return ResourceManager.GetString("Drag_GoBack", resourceCulture)!; }
        }

        public static string Drag_KeepHere {
            get { return ResourceManager.GetString("Drag_KeepHere", resourceCulture)!; }
        }

        public static string Drag_KeepOrGoMessage {
            get { return ResourceManager.GetString("Drag_KeepOrGoMessage", resourceCulture)!; }
        }

        public static string Drag_MergeNotes {
            get { return ResourceManager.GetString("Drag_MergeNotes", resourceCulture)!; }
        }

        public static string Drag_Misplaced {
            get { return ResourceManager.GetString("Drag_Misplaced", resourceCulture)!; }
        }

        public static string Drag_MovedTo {
            get { return ResourceManager.GetString("Drag_MovedTo", resourceCulture)!; }
        }

        public static string Drag_Retry {
            get { return ResourceManager.GetString("Drag_Retry", resourceCulture)!; }
        }

        public static string Drag_RetryHint {
            get { return ResourceManager.GetString("Drag_RetryHint", resourceCulture)!; }
        }

        public static string Drop_Binary {
            get { return ResourceManager.GetString("Drop_Binary", resourceCulture)!; }
        }

        public static string Drop_FileHere {
            get { return ResourceManager.GetString("Drop_FileHere", resourceCulture)!; }
        }

        public static string Drop_Hint {
            get { return ResourceManager.GetString("Drop_Hint", resourceCulture)!; }
        }

        public static string Drop_PartialSuccess {
            get { return ResourceManager.GetString("Drop_PartialSuccess", resourceCulture)!; }
        }

        public static string Drop_ReadFailed {
            get { return ResourceManager.GetString("Drop_ReadFailed", resourceCulture)!; }
        }

        public static string Drop_TooLarge {
            get { return ResourceManager.GetString("Drop_TooLarge", resourceCulture)!; }
        }

        public static string Find_Header {
            get { return ResourceManager.GetString("Find_Header", resourceCulture)!; }
        }

        public static string Find_NoMatches {
            get { return ResourceManager.GetString("Find_NoMatches", resourceCulture)!; }
        }

        public static string Find_Placeholder {
            get { return ResourceManager.GetString("Find_Placeholder", resourceCulture)!; }
        }

        public static string Find_Replace {
            get { return ResourceManager.GetString("Find_Replace", resourceCulture)!; }
        }

        public static string Find_ReplaceAll {
            get { return ResourceManager.GetString("Find_ReplaceAll", resourceCulture)!; }
        }

        public static string Find_ReplacePlaceholder {
            get { return ResourceManager.GetString("Find_ReplacePlaceholder", resourceCulture)!; }
        }

        public static string Help_CloneTab {
            get { return ResourceManager.GetString("Help_CloneTab", resourceCulture)!; }
        }

        public static string Help_Copy {
            get { return ResourceManager.GetString("Help_Copy", resourceCulture)!; }
        }

        public static string Help_Cut {
            get { return ResourceManager.GetString("Help_Cut", resourceCulture)!; }
        }

        public static string Help_DeleteTab {
            get { return ResourceManager.GetString("Help_DeleteTab", resourceCulture)!; }
        }

        public static string Help_DismissHint {
            get { return ResourceManager.GetString("Help_DismissHint", resourceCulture)!; }
        }

        public static string Help_Find {
            get { return ResourceManager.GetString("Help_Find", resourceCulture)!; }
        }

        public static string Help_FocusMinimize {
            get { return ResourceManager.GetString("Help_FocusMinimize", resourceCulture)!; }
        }

        public static string Help_FontDecrease {
            get { return ResourceManager.GetString("Help_FontDecrease", resourceCulture)!; }
        }

        public static string Help_FontIncrease {
            get { return ResourceManager.GetString("Help_FontIncrease", resourceCulture)!; }
        }

        public static string Help_FontReset {
            get { return ResourceManager.GetString("Help_FontReset", resourceCulture)!; }
        }

        public static string Help_NewTab {
            get { return ResourceManager.GetString("Help_NewTab", resourceCulture)!; }
        }

        public static string Help_NextTab {
            get { return ResourceManager.GetString("Help_NextTab", resourceCulture)!; }
        }

        public static string Help_Paste {
            get { return ResourceManager.GetString("Help_Paste", resourceCulture)!; }
        }

        public static string Help_PinUnpin {
            get { return ResourceManager.GetString("Help_PinUnpin", resourceCulture)!; }
        }

        public static string Help_PreviousTab {
            get { return ResourceManager.GetString("Help_PreviousTab", resourceCulture)!; }
        }

        public static string Help_Redo {
            get { return ResourceManager.GetString("Help_Redo", resourceCulture)!; }
        }

        public static string Help_RedoAlt {
            get { return ResourceManager.GetString("Help_RedoAlt", resourceCulture)!; }
        }

        public static string Help_RenameTab {
            get { return ResourceManager.GetString("Help_RenameTab", resourceCulture)!; }
        }

        public static string Help_Save {
            get { return ResourceManager.GetString("Help_Save", resourceCulture)!; }
        }

        public static string Help_SaveAs {
            get { return ResourceManager.GetString("Help_SaveAs", resourceCulture)!; }
        }

        public static string Help_SectionEditor {
            get { return ResourceManager.GetString("Help_SectionEditor", resourceCulture)!; }
        }

        public static string Help_SectionGlobal {
            get { return ResourceManager.GetString("Help_SectionGlobal", resourceCulture)!; }
        }

        public static string Help_SectionTabs {
            get { return ResourceManager.GetString("Help_SectionTabs", resourceCulture)!; }
        }

        public static string Help_SectionView {
            get { return ResourceManager.GetString("Help_SectionView", resourceCulture)!; }
        }

        public static string Help_SelectAll {
            get { return ResourceManager.GetString("Help_SelectAll", resourceCulture)!; }
        }

        public static string Help_ShowHelp {
            get { return ResourceManager.GetString("Help_ShowHelp", resourceCulture)!; }
        }

        public static string Help_Title {
            get { return ResourceManager.GetString("Help_Title", resourceCulture)!; }
        }

        public static string Help_Undo {
            get { return ResourceManager.GetString("Help_Undo", resourceCulture)!; }
        }

        public static string Help_Zoom {
            get { return ResourceManager.GetString("Help_Zoom", resourceCulture)!; }
        }

        public static string Language_RestartButton {
            get { return ResourceManager.GetString("Language_RestartButton", resourceCulture)!; }
        }

        public static string Language_RestartMessage {
            get { return ResourceManager.GetString("Language_RestartMessage", resourceCulture)!; }
        }

        public static string Language_RestartTitle {
            get { return ResourceManager.GetString("Language_RestartTitle", resourceCulture)!; }
        }

        public static string Menu_Cleanup {
            get { return ResourceManager.GetString("Menu_Cleanup", resourceCulture)!; }
        }

        public static string Menu_Exit {
            get { return ResourceManager.GetString("Menu_Exit", resourceCulture)!; }
        }

        public static string Menu_Preferences {
            get { return ResourceManager.GetString("Menu_Preferences", resourceCulture)!; }
        }

        public static string Menu_Recover {
            get { return ResourceManager.GetString("Menu_Recover", resourceCulture)!; }
        }

        public static string Pref_AutoDelete {
            get { return ResourceManager.GetString("Pref_AutoDelete", resourceCulture)!; }
        }

        public static string Pref_AutoDeleteHint {
            get { return ResourceManager.GetString("Pref_AutoDeleteHint", resourceCulture)!; }
        }

        public static string Pref_Days {
            get { return ResourceManager.GetString("Pref_Days", resourceCulture)!; }
        }

        public static string Pref_FontReset {
            get { return ResourceManager.GetString("Pref_FontReset", resourceCulture)!; }
        }

        public static string Pref_FontSize {
            get { return ResourceManager.GetString("Pref_FontSize", resourceCulture)!; }
        }

        public static string Pref_GlobalHotkey {
            get { return ResourceManager.GetString("Pref_GlobalHotkey", resourceCulture)!; }
        }

        public static string Pref_Header {
            get { return ResourceManager.GetString("Pref_Header", resourceCulture)!; }
        }

        public static string Pref_HotkeyHint {
            get { return ResourceManager.GetString("Pref_HotkeyHint", resourceCulture)!; }
        }

        public static string Pref_HotkeyPressKeys {
            get { return ResourceManager.GetString("Pref_HotkeyPressKeys", resourceCulture)!; }
        }

        public static string Pref_HotkeyRecord {
            get { return ResourceManager.GetString("Pref_HotkeyRecord", resourceCulture)!; }
        }

        public static string Pref_Language {
            get { return ResourceManager.GetString("Pref_Language", resourceCulture)!; }
        }

        public static string Pref_LanguageHint {
            get { return ResourceManager.GetString("Pref_LanguageHint", resourceCulture)!; }
        }

        public static string Pref_SectionAbout {
            get { return ResourceManager.GetString("Pref_SectionAbout", resourceCulture)!; }
        }

        public static string Pref_SectionAppearance {
            get { return ResourceManager.GetString("Pref_SectionAppearance", resourceCulture)!; }
        }

        public static string Pref_SectionCleanup {
            get { return ResourceManager.GetString("Pref_SectionCleanup", resourceCulture)!; }
        }

        public static string Pref_SectionLanguage {
            get { return ResourceManager.GetString("Pref_SectionLanguage", resourceCulture)!; }
        }

        public static string Pref_SectionShortcuts {
            get { return ResourceManager.GetString("Pref_SectionShortcuts", resourceCulture)!; }
        }

        public static string Pref_Theme {
            get { return ResourceManager.GetString("Pref_Theme", resourceCulture)!; }
        }

        public static string Pref_ThemeDark {
            get { return ResourceManager.GetString("Pref_ThemeDark", resourceCulture)!; }
        }

        public static string Pref_ThemeLight {
            get { return ResourceManager.GetString("Pref_ThemeLight", resourceCulture)!; }
        }

        public static string Pref_ThemeSystem {
            get { return ResourceManager.GetString("Pref_ThemeSystem", resourceCulture)!; }
        }

        public static string Pref_Version {
            get { return ResourceManager.GetString("Pref_Version", resourceCulture)!; }
        }

        public static string Recovery_Adopt {
            get { return ResourceManager.GetString("Recovery_Adopt", resourceCulture)!; }
        }

        public static string Recovery_EmptyNote {
            get { return ResourceManager.GetString("Recovery_EmptyNote", resourceCulture)!; }
        }

        public static string Recovery_Header {
            get { return ResourceManager.GetString("Recovery_Header", resourceCulture)!; }
        }

        public static string Recovery_More {
            get { return ResourceManager.GetString("Recovery_More", resourceCulture)!; }
        }

        public static string Recovery_TabCount {
            get { return ResourceManager.GetString("Recovery_TabCount", resourceCulture)!; }
        }

        public static string Recovery_TabCount_Few {
            get { return ResourceManager.GetString("Recovery_TabCount_Few", resourceCulture)!; }
        }

        public static string Recovery_TabCount_One {
            get { return ResourceManager.GetString("Recovery_TabCount_One", resourceCulture)!; }
        }

        public static string Recovery_UnknownDesktop {
            get { return ResourceManager.GetString("Recovery_UnknownDesktop", resourceCulture)!; }
        }

        public static string Save_Failed {
            get { return ResourceManager.GetString("Save_Failed", resourceCulture)!; }
        }

        public static string Search_Placeholder {
            get { return ResourceManager.GetString("Search_Placeholder", resourceCulture)!; }
        }

        public static string Title_Default {
            get { return ResourceManager.GetString("Title_Default", resourceCulture)!; }
        }

        public static string Title_DefaultFilename {
            get { return ResourceManager.GetString("Title_DefaultFilename", resourceCulture)!; }
        }

        public static string Title_DefaultFilenameFallback {
            get { return ResourceManager.GetString("Title_DefaultFilenameFallback", resourceCulture)!; }
        }

        public static string Title_DesktopN {
            get { return ResourceManager.GetString("Title_DesktopN", resourceCulture)!; }
        }

        public static string Title_Named {
            get { return ResourceManager.GetString("Title_Named", resourceCulture)!; }
        }

        public static string Toast_CleanedUp {
            get { return ResourceManager.GetString("Toast_CleanedUp", resourceCulture)!; }
        }

        public static string Toast_CleanedUp_Few {
            get { return ResourceManager.GetString("Toast_CleanedUp_Few", resourceCulture)!; }
        }

        public static string Toast_CleanedUp_One {
            get { return ResourceManager.GetString("Toast_CleanedUp_One", resourceCulture)!; }
        }

        public static string Toast_Deleted {
            get { return ResourceManager.GetString("Toast_Deleted", resourceCulture)!; }
        }

        public static string Toast_HotkeyConflict {
            get { return ResourceManager.GetString("Toast_HotkeyConflict", resourceCulture)!; }
        }

        public static string Toast_HotkeyInUse {
            get { return ResourceManager.GetString("Toast_HotkeyInUse", resourceCulture)!; }
        }

        public static string Toast_Merged {
            get { return ResourceManager.GetString("Toast_Merged", resourceCulture)!; }
        }

        public static string Toast_NotesDeleted {
            get { return ResourceManager.GetString("Toast_NotesDeleted", resourceCulture)!; }
        }

        public static string Toast_NotesDeleted_Few {
            get { return ResourceManager.GetString("Toast_NotesDeleted_Few", resourceCulture)!; }
        }

        public static string Toast_NotesDeleted_One {
            get { return ResourceManager.GetString("Toast_NotesDeleted_One", resourceCulture)!; }
        }

        public static string Toast_Recovery {
            get { return ResourceManager.GetString("Toast_Recovery", resourceCulture)!; }
        }

        public static string Toast_Replacements {
            get { return ResourceManager.GetString("Toast_Replacements", resourceCulture)!; }
        }

        public static string Toast_Replacements_Few {
            get { return ResourceManager.GetString("Toast_Replacements_Few", resourceCulture)!; }
        }

        public static string Toast_Replacements_One {
            get { return ResourceManager.GetString("Toast_Replacements_One", resourceCulture)!; }
        }

        public static string Tooltip_Clone {
            get { return ResourceManager.GetString("Tooltip_Clone", resourceCulture)!; }
        }

        public static string Tooltip_Copy {
            get { return ResourceManager.GetString("Tooltip_Copy", resourceCulture)!; }
        }

        public static string Tooltip_Delete {
            get { return ResourceManager.GetString("Tooltip_Delete", resourceCulture)!; }
        }

        public static string Tooltip_Find {
            get { return ResourceManager.GetString("Tooltip_Find", resourceCulture)!; }
        }

        public static string Tooltip_Menu {
            get { return ResourceManager.GetString("Tooltip_Menu", resourceCulture)!; }
        }

        public static string Tooltip_NewTab {
            get { return ResourceManager.GetString("Tooltip_NewTab", resourceCulture)!; }
        }

        public static string Tooltip_Paste {
            get { return ResourceManager.GetString("Tooltip_Paste", resourceCulture)!; }
        }

        public static string Tooltip_Pin {
            get { return ResourceManager.GetString("Tooltip_Pin", resourceCulture)!; }
        }

        public static string Tooltip_PinShort {
            get { return ResourceManager.GetString("Tooltip_PinShort", resourceCulture)!; }
        }

        public static string Tooltip_Redo {
            get { return ResourceManager.GetString("Tooltip_Redo", resourceCulture)!; }
        }

        public static string Tooltip_Save {
            get { return ResourceManager.GetString("Tooltip_Save", resourceCulture)!; }
        }

        public static string Tooltip_SaveAs {
            get { return ResourceManager.GetString("Tooltip_SaveAs", resourceCulture)!; }
        }

        public static string Tooltip_Undo {
            get { return ResourceManager.GetString("Tooltip_Undo", resourceCulture)!; }
        }

        public static string Tooltip_Unpin {
            get { return ResourceManager.GetString("Tooltip_Unpin", resourceCulture)!; }
        }

        public static string Tooltip_UnpinShort {
            get { return ResourceManager.GetString("Tooltip_UnpinShort", resourceCulture)!; }
        }

        public static string Welcome_Content {
            get { return ResourceManager.GetString("Welcome_Content", resourceCulture)!; }
        }

        public static string Welcome_Title {
            get { return ResourceManager.GetString("Welcome_Title", resourceCulture)!; }
        }
    }
}
